#!/usr/bin/env python
"""
Generate content-matching illustrations for a Dr.Maya knowledge video.

Each scene/beat that names a concrete thing ("bé đi tiêm", "đo nhiệt độ",
"cho bú", "tắm bé"...) gets a soft flat illustration generated by
Pollinations (free, no API key) and DOWNLOADED LOCALLY to assets/img/ so
the HyperFrames render never depends on network.

Usage:
    python gen_content_images.py cues.json [out_dir]

cues.json format — list of {slug, prompt}:
    [
      {"slug": "scene-01", "prompt": "mother checking baby temperature with thermometer"},
      {"slug": "card-tiem", "prompt": "baby getting a vaccine shot at clinic, gentle nurse"}
    ]

Output: assets/img/<slug>.jpg  (720x720)

SSL note (this machine): needs truststore. The script injects it if available.
"""
import sys, os, json, urllib.parse

# This machine has a corporate-style cert issue; truststore makes httpx use the OS store.
try:
    import truststore; truststore.inject_into_ssl()
except Exception:
    pass

try:
    import httpx
except ImportError:
    sys.exit("Cần httpx: pip install httpx truststore")

# Keep the visual language consistent with the Dr.Maya design system.
STYLE_SUFFIX = ("soft flat vector illustration, warm yellow and cream pastel tones, "
                "minimal cute, mom and baby care, white background")

def gen(cues, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    ok = 0
    for i, c in enumerate(cues):
        slug = c["slug"]
        prompt = f'{c["prompt"]}, {STYLE_SUFFIX}'
        seed = c.get("seed", 7 + i)
        url = ("https://image.pollinations.ai/prompt/"
               + urllib.parse.quote(prompt)
               + f"?width=720&height=720&nologo=true&seed={seed}")
        dest = os.path.join(out_dir, f"{slug}.jpg")
        try:
            r = httpx.get(url, timeout=120, follow_redirects=True)
            if r.status_code == 200 and len(r.content) > 5000:
                with open(dest, "wb") as f:
                    f.write(r.content)
                print(f"  OK  {slug}.jpg  ({len(r.content)} bytes)")
                ok += 1
            else:
                print(f"  FAIL {slug}: status {r.status_code} / {len(r.content)}b")
        except Exception as e:
            print(f"  FAIL {slug}: {type(e).__name__} {str(e)[:80]}")
    print(f"Done: {ok}/{len(cues)} images -> {out_dir}")
    return ok

if __name__ == "__main__":
    if len(sys.argv) < 2:
        sys.exit("Usage: python gen_content_images.py cues.json [out_dir]")
    cues = json.load(open(sys.argv[1], encoding="utf-8"))
    out_dir = sys.argv[2] if len(sys.argv) > 2 else "assets/img"
    gen(cues, out_dir)
